name: CI

on:
  push:
    branches:
      - main   

jobs:
  build:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Corepack and prepare Yarn 4.9.2
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Check yarn versions
        run: |
          echo "Global yarn version"
          yarn --version
          echo "Corepack yarn version"
          corepack yarn --version

      - name: Install dependencies
        run: corepack yarn install --immutable

      - name: Build project
        run: corepack yarn workspace api build

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .

      - name: Push image
        run: docker push rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}
